# Generated by Django 4.0.4 on 2022-04-27 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateKalib', models.DateField(default=django.utils.timezone.now, verbose_name='Дата калибровки')),
                ('konstant', models.CharField(max_length=9, verbose_name='Текущая константа')),
                ('dateKalibNext', models.DateField(verbose_name='Следующая дата калибровки')),
            ],
        ),
        migrations.CreateModel(
            name='Viscosimetrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.CharField(max_length=5, verbose_name='Диаметр')),
                ('serialNumber', models.CharField(max_length=30, verbose_name='Заводской номер')),
                ('Viscosity1000', models.CharField(max_length=30, verbose_name='За 1000 сек, сСт')),
                ('dateKalib', models.DateField(default=django.utils.timezone.now, verbose_name='Дата калибровки')),
                ('datePov', models.DateField(verbose_name='Дата поверки')),
                ('datePovDedlain', models.DateField(verbose_name='Дата окончания поверки')),
                ('range', models.CharField(max_length=30, verbose_name='Диаметр')),
                ('konstant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kalibration')),
            ],
        ),
    ]
