# Generated by Django 4.0.4 on 2022-04-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kalibration',
            options={'verbose_name': 'Калибровка', 'verbose_name_plural': 'Калибровки'},
        ),
        migrations.AlterModelOptions(
            name='viscosimetrs',
            options={'verbose_name': 'Вискозиметр', 'verbose_name_plural': 'Вискозиметры'},
        ),
    ]
