# Generated by Django 4.0.4 on 2022-04-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_manufacturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='viscosimetrs',
            name='konstant',
        ),
        migrations.DeleteModel(
            name='Kalibration',
        ),
        migrations.DeleteModel(
            name='Viscosimetrs',
        ),
    ]
